function mlist = metric_list()

mlist = { ...
'alex-Volume', ...
'alex-FirstOrder', ...
'alex-Cooccur', ...
'alex-RLM', ...
'alex-Cooccur-R2', ...
'alex-RLM-R2', ...
'alex-Cooccur-R4', ...
'alex-RLM-R4', ...
'maya-inner-Volume', ...
'maya-inner-FirstOrder', ...
'maya-inner-Cooccur', ...
'maya-inner-RLM', ...
'maya-inner-Cooccur-R2', ...
'maya-inner-RLM-R2', ...
'maya-inner-Cooccur-R4', ...
'maya-inner-RLM-R4', ...
'maya-outer-Volume', ...
'maya-outer-FirstOrder', ...
'maya-outer-Cooccur', ...
'maya-outer-RLM', ...
'maya-both-Volume', ...
'maya-both-FirstOrder', ...
'maya-both-Cooccur', ...
'maya-both-RLM', ...
'maya-both-Cooccur-R2', ...
'maya-both-RLM-R2', ...
'maya-both-Cooccur-R4', ...
'maya-both-RLM-R4', ...
};