#$ -S /bin/bash

# process one pair of images in the Empire10 database

IMAGENAME=$1
TESTCASE=$2

# DISP=echo
# DISP=

ANTSDIRECTORY=/home/songgang/project/ANTS/gccrel/bin
C3D=/home/songgang/pkg/bin/c3d
NICKDIRECOTRY=/home/songgang/project/tustison/Utilities/gccrel

ANTS=${ANTSDIRECTORY}/ANTS
WARPIMAGE=${ANTSDIRECTORY}/WarpImageMultiTransform
COMPOSEWARP=${ANTSDIRECTORY}/ComposeMultiTrnasform
MEASURESIM=${ANTSDIRECTORY}/MeasureImageSimilarity
IMAGEMATH=${ANTSDIRECTORY}/ImageMath

INPUTROOT=/home/songgang/project/Empire10/Empire10_thesis/Input/original

PREPROCESSROOT=/home/songgang/project/Empire10/Empire10_thesis/Input/rescaled_padded

OUTPUTROOT=/home/songgang/project/Empire10/Empire10_thesis/Output/${TESTCASE}

REGPREFIX=$OUTPUTROOT/$IMAGENAME/${IMAGENAME}_${TESTCASE}_fix2mov

FIXEDIMAGE=$INPUTROOT/scans/${IMAGENAME}_Fixed.nii.gz
FIXEDMASK=$INPUTROOT/lungMasks/${IMAGENAME}_FixedMask.nii.gz
MOVINGIMAGE=$INPUTROOT/scans/${IMAGENAME}_Moving.nii.gz
MOVINGMASK=$INPUTROOT/lungMasks/${IMAGENAME}_MovingMask.nii.gz

FIXPREPROCESS=$PREPROCESSROOT/scans/${IMAGENAME}_Fixed_rescaled_padded.nii.gz
MOVPREPROCESS=$PREPROCESSROOT/scans/${IMAGENAME}_Moving_rescaled_padded.nii.gz

FIXMASKPREPROCESS=$PREPROCESSROOT/lungMasks/${IMAGENAME}_FixedMask_padded.nii.gz
MOVMASKPREPROCESS=$PREPROCESSROOT/lungMasks/${IMAGENAME}_MovingMask_padded.nii.gz

LOGFILE=${REGPREFIX}ANTSCall.txt
# LOGFILE=/dev/stdout

if [ ! -d `dirname $LOGFILE` ]
	then
	$DISP mkdir -p `dirname $LOGFILE`
fi

echo "start the log file at: "  `date` > $LOGFILE

function preprocess
{
	INPUTIMAGE=$1
	MASKIMAGE=$2
	OUTPUTIMAGE=$3

	T1=`dirname $OUTPUTIMAGE`
	T2=`basename $OUTPUTIMAGE`
	T3=${T2%%.*} # get /A/B/C.nii.gz to /A/B/C
	OUTPUTPREFIX=$T1/${T3}

	if [ ! -d `dirname $OUTPUTIMAGE` ]
		then
		$DISP mkdir -p `dirname $OUTPUTIMAGE`
	fi

	$DISP $C3D $INPUTIMAGE $MASKIMAGE -times -o $OUTPUTPREFIX"tmp1.nii.gz"
	$DISP ${NICKDIRECOTRY}/RescaleImageIntensity 3 $OUTPUTPREFIX"tmp1.nii.gz" $OUTPUTPREFIX"tmp2.nii.gz" 0 1
	$DISP $C3D $OUTPUTPREFIX"tmp2.nii.gz" -scale -1 -shift 1 $MASKIMAGE -times -o $OUTPUTPREFIX"tmp3.nii.gz"
	$DISP $ANTSDIRECTORY/ImageMath 3 $OUTPUTIMAGE PadImage $OUTPUTPREFIX"tmp3.nii.gz" 10

	$DISP rm $OUTPUTPREFIX"tmp3.nii.gz"
	$DISP rm $OUTPUTPREFIX"tmp2.nii.gz"
	$DISP rm $OUTPUTPREFIX"tmp1.nii.gz"

}

function preprocess_mask
{
	MASKIMAGE=$1
	OUTPUTMASK=$2

	if [ ! -d `dirname $OUTPUTMASK` ]
		then
		$DISP mkdir -p `dirname $OUTPUTMASK`
	fi

	$DISP $ANTSDIRECTORY/ImageMath 3 $OUTPUTMASK PadImage $MASKIMAGE 10
}


function register
{
	DIMENSION=3
	FIXEDIMAGE=$1
	MOVINGIMAGE=$2
	FIXEDMASK=$3
	MOVINGMASK=$4
	REGPREFIX=$5


	AFFINEMETRIC="MSQ[$FIXEDMASK,$MOVINGMASK,1]"

	gradient_step=0.25
#	time_step=
#	intergration_delta=

	gradient_sigma=6.0
	total_field_sigma=0

	deformable_iteratons=200x200x200x200x50
	# deformable_iteratons=20x0x0x0x0
	metric_radius=2

	# TRANSFORM="SyN[$gradient_step,$time_step,$intergration_delta]"
	TRANSFORM="SyN[$gradient_step]"
	REGULARIZATON="Gauss[$gradient_sigma,$total_field_sigma]"
	DEFORMMETRIC="CC[$FIXEDIMAGE,$MOVINGIMAGE,1,$metric_radius]"

	echo "start here!" >> $LOGFILE
	echo >> $LOGFILE
	echo "initial affine transform" >> $LOGFILE
	echo "start date: " `date` >> $LOGFILE

	#bash grammar: no space in the new line after \
	MYARGS="$ANTS $DIMENSION -o ${REGPREFIX}initaff "\
"-m $AFFINEMETRIC "\
"-i 0 "\
"-t $TRANSFORM "\
"-r $REGULARIZATON "\
"--affine-metric-type MI "\
"--number-of-affine-iterations 10000x10000x10000x10000"
	echo $MYARGS >> $LOGFILE
	$DISP $MYARGS >> $LOGFILE 2>&1

	echo >> $LOGFILE
	echo "deformable transform" >> $LOGFILE
	echo "start date: " `date` >> $LOGFILE
	MYARGS="$ANTS $DIMENSION -o ${REGPREFIX} "\
"-m $DEFORMMETRIC "\
"-i $deformable_iteratons "\
"-t $TRANSFORM "\
"-r $REGULARIZATON "\
"--affine-metric-type MI "\
"--initial-affine ${REGPREFIX}initaffAffine.txt "\
"--continue-affine false"
	echo $MYARGS >> $LOGFILE
	$DISP $MYARGS >> $LOGFILE 2>&1

	echo >> $LOGFILE
	echo "end registration date:" `date` >> $LOGFILE
}

function postprocess
{
	FIXEDIMAGE=$1
	MOVINGIMAGE=$2
	REGPREFIX=$3

	DIMENSION=3

	DEFORMEDIMAGE=${REGPREFIX}deformed.nii.gz

	VECTORFIELD=${REGPREFIX}Warp.nii.gz # generated by ANTS
	AFFINEFILE=${REGPREFIX}Affine.txt		# generated by ANTS

	echo >> $LOGFILE
	echo "warp the moving image" >> $LOGFILE
	echo "start date: " `date` >> $LOGFILE

	MYARGS="$WARPIMAGE $DIMENSION $MOVINGIMAGE $DEFORMEDIMAGE $VECTORFIELD $AFFINEFILE -R $FIXEDIMAGE"
	echo $MYARGS >> $LOGFILE
	$DISP $MYARGS >> $LOGFILE 2>&1
	echo "end post-process date:" `date` >> $LOGFILE
	# start a new metric file

	METRICFILE=${REGPREFIX}metricCC.txt
	echo > $METRICFILE
	echo "compute the similarity" >> $METRICFILE
	
	echo "start date: " `date` >> $METRICFILE
	MYARGS="$IMAGEMATH 3 void.txt NeighborhoodCorrelation $FIXEDIMAGE $DEFORMEDIMAGE 5"
	    echo $MYARGS >> $METRICFILE
	$DISP $MYARGS >> $METRICFILE 2>&1    
	echo >> $METRICFILE

	echo "start date: " `date` >> $METRICFILE
	MYARGS="$IMAGEMATH 3 void.txt NormalizedCorrelation $FIXEDIMAGE $DEFORMEDIMAGE"
	    echo $MYARGS >> $METRICFILE
	$DISP $MYARGS >> $METRICFILE 2>&1    
	echo >> $METRICFILE

	echo "start date: " `date` >> $METRICFILE
	MYARGS="$IMAGEMATH 3 void.txt PearsonCorrelation $FIXEDIMAGE $DEFORMEDIMAGE"
	    echo $MYARGS >> $METRICFILE
	$DISP $MYARGS >> $METRICFILE 2>&1    
	echo >> $METRICFILE



	echo "end metric date:" `date` >> $METRICFILE
}


function postprocess_affine_only
{
	FIXEDIMAGE=$1
	MOVINGIMAGE=$2
	REGPREFIX=$3

	DIMENSION=3

	AFFINEONLYIMAGE=${REGPREFIX}affineonly.nii.gz

	VECTORFIELD=${REGPREFIX}Warp.nii.gz # generated by ANTS
	AFFINEFILE=${REGPREFIX}Affine.txt		# generated by ANTS

	echo >> $LOGFILE
	echo "warp the moving image only using affine transform" >> $LOGFILE
	echo "start date: " `date` >> $LOGFILE

	MYARGS="$WARPIMAGE $DIMENSION $MOVINGIMAGE $AFFINEONLYIMAGE $AFFINEFILE -R $FIXEDIMAGE"
	echo $MYARGS >> $LOGFILE
	$DISP $MYARGS >> $LOGFILE 2>&1
	echo "end post-process date:" `date` >> $LOGFILE
	# start a new metric file

	METRICFILE=${REGPREFIX}metricCC_affineonly.txt
	echo > $METRICFILE
	echo "compute the similarity for affine only" >> $METRICFILE
	
	echo "start date: " `date` >> $METRICFILE
	MYARGS="$IMAGEMATH 3 void.txt NeighborhoodCorrelation $FIXEDIMAGE $AFFINEONLYIMAGE 5"
	    echo $MYARGS >> $METRICFILE
	$DISP $MYARGS >> $METRICFILE 2>&1    
	echo >> $METRICFILE

	echo "start date: " `date` >> $METRICFILE
	MYARGS="$IMAGEMATH 3 void.txt NormalizedCorrelation $FIXEDIMAGE $AFFINEONLYIMAGE"
	    echo $MYARGS >> $METRICFILE
	$DISP $MYARGS >> $METRICFILE 2>&1    
	echo >> $METRICFILE

		echo "start date: " `date` >> $METRICFILE
	MYARGS="$IMAGEMATH 3 void.txt PearsonCorrelation $FIXEDIMAGE $AFFINEONLYIMAGE"
	    echo $MYARGS >> $METRICFILE
	$DISP $MYARGS >> $METRICFILE 2>&1    
	echo >> $METRICFILE


	echo "end metric date:" `date` >> $METRICFILE
}

# preprocess $FIXEDIMAGE $FIXEDMASK $FIXPREPROCESS
# preprocess $MOVINGIMAGE $MOVINGMASK $MOVPREPROCESS
# preprocess_mask $FIXEDMASK $FIXMASKPREPROCESS
# preprocess_mask $MOVINGMASK $MOVMASKPREPROCESS

register $FIXPREPROCESS $MOVPREPROCESS $FIXMASKPREPROCESS $MOVMASKPREPROCESS $REGPREFIX

postprocess $FIXPREPROCESS $MOVPREPROCESS $REGPREFIX
postprocess_affine_only $FIXPREPROCESS $MOVPREPROCESS $REGPREFIX
